// ============================================================
// AKV GLOBAL CONSULTANCY — Property & Community Data
// ============================================================

export const PROPERTIES = [
  {
    id: 1,
    type: 'Penthouse',
    name: 'Skyline Residences',
    location: 'Downtown Dubai',
    beds: 4, baths: 5, area: '6,200',
    price: 'AED 18,500,000',
    badge: 'Featured',
    img: 'images/penthouse.png',
    isLarge: true,
    desc: 'An extraordinary penthouse with panoramic views of Burj Khalifa and the Dubai Fountain, featuring a private pool terrace and bespoke interior finishing.',
    amenities: ['Private Rooftop Pool','Concierge Service','Home Automation','Private Elevator','Wine Cellar','Chef\'s Kitchen','Cinema Room','Spa & Steam'],
    developer: 'Emaar Properties',
    offplan: false,
    community: 'Downtown Dubai',
    category: 'Penthouse',
  },
  {
    id: 2,
    type: 'Villa',
    name: 'The Palm Grove Estate',
    location: 'Palm Jumeirah',
    beds: 6, baths: 7, area: '9,800',
    price: 'AED 42,000,000',
    badge: 'Exclusive',
    img: 'images/villa.png',
    isLarge: false,
    desc: 'A masterfully crafted beachfront villa on Palm Jumeirah fronds, offering private beach access, a vanishing-edge pool, and unobstructed Arabian Gulf views.',
    amenities: ['Private Beach','Infinity Pool','Boat Dock','Home Cinema','Gym & Spa','Staff Quarters','Landscaped Garden','Security System'],
    developer: 'Nakheel',
    offplan: false,
    community: 'Palm Jumeirah',
    category: 'Villa',
  },
  {
    id: 3,
    type: 'Apartment',
    name: 'Marina Gate Residences',
    location: 'Dubai Marina',
    beds: 3, baths: 4, area: '2,850',
    price: 'AED 4,200,000',
    badge: null,
    img: 'images/apartment.png',
    isLarge: false,
    desc: 'A sophisticated 3-bedroom apartment in Marina Gate with sweeping marina views, premium fixtures, and direct access to the Marina Walk.',
    amenities: ['Pool Deck','Fitness Centre','Marina Access','Concierge','Covered Parking','High-Speed Lifts','24/7 Security'],
    developer: 'Select Group',
    offplan: false,
    community: 'Dubai Marina',
    category: 'Apartment',
  },
  {
    id: 4,
    type: 'Off-Plan Apartment',
    name: 'Canopy Heights',
    location: 'Dubai Hills Estate',
    beds: 2, baths: 3, area: '1,650',
    price: 'AED 2,800,000',
    badge: 'Off-Plan',
    img: 'images/offplan.png',
    isLarge: false,
    desc: 'Contemporary residences within Dubai Hills Estate, surrounded by the championship golf course, parks, and world-class retail.',
    amenities: ['Infinity Pool','Golf Views','Kids Play Area','BBQ Terraces','Retail Boulevard','Yoga Deck'],
    developer: 'Emaar Properties',
    offplan: true,
    completion: 'Q4 2026',
    paymentPlan: '50/50',
    community: 'Dubai Hills Estate',
    category: 'Apartment',
  },
  {
    id: 5,
    type: 'Penthouse',
    name: 'One Business Bay',
    location: 'Business Bay',
    beds: 5, baths: 6, area: '7,400',
    price: 'AED 28,000,000',
    badge: 'Premium',
    img: 'images/penthouse.png',
    isLarge: false,
    desc: 'An iconic dual-floor penthouse crowning one of Business Bay\'s most prestigious towers, with panoramic views across the Dubai Canal and Downtown skyline.',
    amenities: ['Dual-Level Layout','Private Terrace Pool','360° Views','Smart Home','Cinema','Wine Room'],
    developer: 'Damac',
    offplan: false,
    community: 'Business Bay',
    category: 'Penthouse',
  },
  {
    id: 6,
    type: 'Townhouse',
    name: 'Arabella Townhouses',
    location: 'Arabian Ranches',
    beds: 4, baths: 4, area: '3,200',
    price: 'AED 3,600,000',
    badge: null,
    img: 'images/villa.png',
    isLarge: false,
    desc: 'Elegant cluster townhouses in the heart of Arabian Ranches, offering a serene community lifestyle with lush greenery and equestrian facilities nearby.',
    amenities: ['Private Garden','Community Pool','Clubhouse','Equestrian Club Access','Kids Park','Walking Trails'],
    developer: 'Emaar Properties',
    offplan: false,
    community: 'Arabian Ranches',
    category: 'Townhouse',
  },
];

export const OFFPLAN = [
  {
    id: 'op1',
    name: 'Elara at The Valley',
    developer: 'Emaar Properties',
    location: 'The Valley, Dubai',
    price: 'AED 1,450,000',
    paymentPlan: '80/20',
    completion: 'Q2 2027',
    img: 'images/offplan.png',
    beds: 3, baths: 3, area: '2,100',
  },
  {
    id: 'op2',
    name: 'Damac Bay by Cavalli',
    developer: 'Damac',
    location: 'Dubai Harbour',
    price: 'AED 3,900,000',
    paymentPlan: '70/30',
    completion: 'Q3 2027',
    img: 'images/penthouse.png',
    beds: 4, baths: 5, area: '4,300',
  },
  {
    id: 'op3',
    name: 'Sobha Hartland II',
    developer: 'Sobha Realty',
    location: 'Mohammed Bin Rashid City',
    price: 'AED 2,100,000',
    paymentPlan: '60/40',
    completion: 'Q1 2027',
    img: 'images/apartment.png',
    beds: 2, baths: 3, area: '1,650',
  },
];

export const COMMUNITIES = [
  {
    id: 'downtown',
    name: 'Downtown Dubai',
    tagline: 'The city\'s iconic heart',
    desc: 'Home to the Burj Khalifa, Dubai Mall and the Dubai Fountain — the world-famous Downtown district is the pinnacle of urban luxury living.',
    img: 'images/downtown_dubai.png',
    stats: { avgPrice: 'AED 2.8M', roi: '5.2%', props: '1,200+', type: 'Apartments & Penthouses' },
    lifestyle: 'Iconic city living at its finest, with world-class dining, retail, and cultural experiences on your doorstep.',
    highlights: [
      { icon: 'building', title: 'Burj Khalifa Views', desc: 'Properties with iconic skyline perspectives' },
      { icon: 'shopping', title: 'Dubai Mall Access', desc: 'World\'s largest shopping destination nearby' },
      { icon: 'dining', title: 'Fine Dining', desc: 'Michelin-starred restaurants & rooftop bars' },
      { icon: 'trending', title: 'Strong ROI', desc: '5.2% average rental yield in 2024' },
    ],
    faqs: [
      { q: 'What is the average property price in Downtown Dubai?', a: 'Apartments typically range from AED 1.8M for studios to over AED 20M for penthouses, with an average around AED 2.8M.' },
      { q: 'Is Downtown Dubai a good investment?', a: 'Yes, Downtown Dubai consistently delivers strong rental yields of 4.5–6% and benefits from the highest tourist footfall in the UAE.' },
      { q: 'What property types are available?', a: 'Primarily high-rise apartments and penthouses. A limited number of hotel-branded residences are also available.' },
    ],
  },
  {
    id: 'marina',
    name: 'Dubai Marina',
    tagline: 'Urban waterfront living',
    desc: 'A vibrant waterfront district with 3.5km of yacht-lined canal, world-class residences, dining, and the famous Marina Walk.',
    img: 'images/dubai_marina.png',
    stats: { avgPrice: 'AED 2.2M', roi: '6.1%', props: '2,400+', type: 'Apartments & Marina Views' },
    lifestyle: 'Dynamic, cosmopolitan lifestyle with a Mediterranean-inspired atmosphere and stunning marina vistas.',
    highlights: [
      { icon: 'anchor', title: 'Yacht Marina', desc: 'Private berths for luxury vessels' },
      { icon: 'waves', title: 'JBR Beach', desc: 'Walking distance to Jumeirah Beach Residence' },
      { icon: 'star', title: 'Nightlife', desc: 'Premium bars, clubs and entertainment' },
      { icon: 'trending', title: 'High Yield', desc: '6.1% average rental yield — top performing area' },
    ],
    faqs: [
      { q: 'What are average prices in Dubai Marina?', a: 'Prices range from AED 900K for studio apartments to AED 8M+ for large penthouses with full marina views.' },
      { q: 'Is Dubai Marina popular with short-term rentals?', a: 'Absolutely. Marina is one of Dubai\'s top short-term rental destinations, with strong demand year-round from tourists and business travellers.' },
      { q: 'What transport is available?', a: 'Dubai Metro (Red Line), Dubai Tram, water taxis, and abundant taxi/ride-hail services make Marina extremely accessible.' },
    ],
  },
  {
    id: 'palm',
    name: 'Palm Jumeirah',
    tagline: 'The world\'s most iconic address',
    desc: 'The legendary man-made island offers the most prestigious residential address in the Middle East, with private beaches and celebrity neighbours.',
    img: 'images/palm_jumeirah.png',
    stats: { avgPrice: 'AED 8.5M', roi: '4.8%', props: '800+', type: 'Villas & Luxury Apartments' },
    lifestyle: 'Ultra-exclusive island living with private beaches, luxury hotels, and unrivalled prestige.',
    highlights: [
      { icon: 'waves', title: 'Private Beaches', desc: 'Direct beach access from frond villas' },
      { icon: 'hotel', title: 'Atlantis & Beyond', desc: 'World-class hotels and entertainment' },
      { icon: 'compass', title: 'Arabian Gulf', desc: '360-degree sea and skyline views' },
      { icon: 'shield', title: 'Exclusivity', desc: 'Gated security and controlled access' },
    ],
    faqs: [
      { q: 'What is the most sought-after property type on Palm Jumeirah?', a: 'Frond villas with private beach access are the most coveted, followed by high-floor apartments in luxury buildings like One Palm and XXII Carat.' },
      { q: 'What is the price range for Palm Jumeirah villas?', a: 'Villas range from approximately AED 12M for smaller frond properties to over AED 100M for signature mansions.' },
      { q: 'Is Palm Jumeirah a good long-term investment?', a: 'Yes. Its unique geography ensures supply limitations, sustained demand, and consistent capital appreciation.' },
    ],
  },
];

export const INSIGHTS = [
  { id: 1, cat: 'Market Update', date: 'July 2025', title: 'Dubai Real Estate Achieves Record Transaction Volumes in H1 2025', img: 'images/downtown_dubai.png' },
  { id: 2, cat: 'Investment Guide', date: 'June 2025', title: 'Off-Plan vs. Ready Properties: Where Should You Invest in 2025?', img: 'images/offplan.png' },
  { id: 3, cat: 'Community Guide', date: 'May 2025', title: 'Dubai Hills Estate: The Complete Buyer\'s Guide for 2025', img: 'images/villa.png' },
];

export const TESTIMONIALS = [
  {
    text: '"AKV Global guided us through our first Dubai investment with extraordinary expertise. From shortlisting properties to final handover — the process was seamless."',
    name: 'James & Catherine Whitmore',
    role: 'International Investors — UK',
    avatar: 'https://i.pravatar.cc/100?img=11'
  },
  {
    text: '"I had been searching for a penthouse in Downtown Dubai for over a year. AKV found me exactly what I wanted within three weeks. Remarkable service."',
    name: 'Khalid Al-Rashidi',
    role: 'Property Buyer — Abu Dhabi',
    avatar: 'https://i.pravatar.cc/100?img=12'
  },
  {
    text: '"The team\'s deep knowledge of the off-plan market gave us the confidence to invest in Dubai. Our portfolio has grown by 34% in two years."',
    name: 'Anjali & Vikram Mehta',
    role: 'Investment Clients — India',
    avatar: 'https://i.pravatar.cc/100?img=33'
  },
  {
    text: '"As an expat relocating to Dubai, finding a home in Palm Jumeirah felt overwhelming. AKV Global found us a beachfront villa in record time. Fantastic experience!"',
    name: 'Marc Casado',
    role: 'Shop Store Owner — Spain',
    avatar: 'https://i.pravatar.cc/100?img=60'
  },
  {
    text: '"Their property management services are second to none. I live overseas and trust AKV fully to manage my rental units and keep yields optimized."',
    name: 'Sarah Jenkins',
    role: 'Landlord — Australia',
    avatar: 'https://i.pravatar.cc/100?img=47'
  },
  {
    text: '"Highly professional, responsive, and completely transparent with fees. They helped me sell my Marina gate apartment for a premium price."',
    name: 'David Elson',
    role: 'Seller — Dubai Marina',
    avatar: 'https://i.pravatar.cc/100?img=49'
  }
];
